server:
  port: 0

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=false&serverTimezone=UTC
    username: root
    password: ''

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    # Each node gets a unique ID in Eureka
    instance-id: ${spring.application.name}:${random.value}
    # Optional: register the IP address rather than hostname
    prefer-ip-address: true

jwt:
  secret: mySuperSecretKeyWhichIsVeryLongAndSecure12345
  expiration-ms: 3600000
