server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
    loadbalancer:
      retry:
        enabled: true
        max-attempts: 3
    gateway:
      discovery:
        locator:
          enabled: false 
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: users
          uri: lb://auth-service
          predicates:
            - Path=/users/**

        - id: courses
          uri: lb://courses-service
          predicates:
            - Path=/courses/**
            
        - id: subscriptions 
          uri: lb://courses-service
          predicates:
            - Path=/subscriptions/**

        - id: exams 
          uri: lb://exam-service
          predicates:
            - Path=/exams/**

        - id: payment
          uri: lb://payment-service
          predicates:
            - Path=/payments/**        

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
